### ISSUE TITLE
Generate an ops file after terraform apply finished

### ISSUE THREAD

**Issue by norshtein** [kun-lun/infra-producer#15]
According to Andy, after the `terraform apply` finished, the infra producer should fetch the outputs of terraform and generate an ops file(similar as bosh). For example:
```yaml
- type: replace
  path: /vm_groups/name=web-servers/networks/outputs?
  value: 
    - ip: 10.0.0.6
    - ip: 10.0.0.7
    - ip: 10.0.0.8
```
